I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script
    with dissolve(0.5)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 50, in script
    with dissolve(0.5)
  File "P:\RenPy\renpy-7.2.2-sdk\renpy\ast.py", line 1375, in execute
    renpy.exports.with_statement(trans, paired)
  File "P:\RenPy\renpy-7.2.2-sdk\renpy\exports.py", line 1578, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "P:\RenPy\renpy-7.2.2-sdk\renpy\display\core.py", line 2240, in do_with
    clear=clear)
  File "P:\RenPy\renpy-7.2.2-sdk\renpy\display\core.py", line 2690, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "P:\RenPy\renpy-7.2.2-sdk\renpy\display\core.py", line 3027, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-8-6.2.9200
Ren'Py 7.2.2.491
T 1.0
Sun May 05 22:44:36 2019
